### ISSUE TITLE
Document customizing by patch-package?

### ISSUE THREAD

**Issue by brodybits** [papercss/papercss#10]
I recently discovered `patch-package` which makes it easy to customize without the need for forking.

I would be happy to contribute documentation assuming this project keeps a permissive license (#9), will need a few weeks due to existing commitments.

**Comment by rhyneav** [comment]
Patch-package looks interesting, but is it only for patching NPM modules? I'm all for adding it (and cool new things in general), but I just want to understand where this would be useful first.

And yes, this project will keep a permissive license. I'll work on making that more explicit.

**Comment by brodybits** [comment]
> Patch-package looks interesting, but is it only for patching NPM modules?

I think yes, at least so far (gotta admit I haven't tried it myself). My idea was just to document it as an option. Maybe not so relevant since I realized this project is more of a starter template. (It would be nice to see PaperCSS as a reusable HTML or web component, when we have convergence someday.)

> And yes, this project will keep a permissive license. I'll work on making that more explicit.

Thanks for the response.

**Comment by rhyneav** [comment]
Hey @brodybits I'm going to go ahead and close this for now. Feel free to reopen if you want to go in and add details on Patch-package! I think it could be useful for those wanting to override some PaperCSS styles if they `npm install papercss`
