### ISSUE TITLE
Include animation

### ISSUE THREAD

**Issue by muyaszed** [papercss/papercss#101]
I stumble upon this library which is purely using css. It would be great if we could include some animation library for papercss

https://github.com/daneden/animate.css

**Comment by muyaszed** [comment]
I would like to add this item to a new test card in projects, but I can't find the exact button to do that.

**Comment by rhyneav** [comment]
I'm going to ping @Fraham for this. He is currently the man with the pan for projects.

**Comment by Fraham** [comment]
Added to the features project

**Comment by Rach-Coster** [comment]
Could I have a go at including animation to Paper Css? It looks like the least daunting thing I can do for this amazing project @Fraham

**Comment by Rach-Coster** [comment]
Can we also put the label 'beginner friendly' to this issue please :)

**Comment by TotomInc** [comment]
Of course you can @Rach-Coster!

**Comment by rhyneav** [comment]
Awesome! What components specifically will get animations?

**Comment by tan-ahmed** [comment]
GSAP is the standard animation library, besides a fadeIn you can write up in like a few mins, I cant see what sort of benefit it may add at all. You could even use animate.css along side this library, its pretty much reinventing the wheel.

**Comment by rhyneav** [comment]
Since this issue is a few years stale at this point, I'm going to close it. PaperCSS is going to remain a simple CSS framework that can be used alongside other frameworks like animate.css.
