### ISSUE TITLE
1.3.0 is broken, need to prepare 1.3.1

### ISSUE THREAD

**Issue by TotomInc** [papercss/papercss#116]
Just realized that 1.3.0 is broken, due to missing imports in `modals.less`, when running `gulp build`. I've just fixed it and I'm going to do a PR, but @rhyneav you need to prepare for 1.3.1 please.

**Comment by afzalsayed96** [comment]
This was my mistake sorry about that :(

**Comment by rhyneav** [comment]
All good everyone! Things should be back to normal with [v1.3.1](https://github.com/papercss/papercss/releases). If nothing else, it's pretty easy to pump out 1.3.2 if need be :)
