### ISSUE TITLE
Presentation issue in mobile

### ISSUE THREAD

**Issue by afzalsayed96** [papercss/papercss#120]
- There is slight scroll in the right direction on mobile. Although, coincidentally a pinch of imperfection is the theme of framework 😉  it can create a bad impression for a CSS framework to allow scrolling with no content.

![1](https://user-images.githubusercontent.com/14029371/34113738-afd26604-e436-11e7-84db-6ff2e3720f65.jpg)

- Paper buttons have `background: transparent` and `display: inline` which looks weird in mobile.

![2](https://user-images.githubusercontent.com/14029371/34114271-5a01312c-e438-11e7-88c2-16046a9483ba.jpg)

**Comment by afzalsayed96** [comment]
The solution for button problem here might be changing CSS property to `display: inline-block` and `background: white`

**Comment by koester** [comment]
This should be closed as it was fixed in 1.4.0
