### ISSUE TITLE
Switch component

### ISSUE THREAD

**Issue by antoninadert** [papercss/papercss#121]
As we have paper checkboxes, another flavor of the same is the switch component:

![image](https://user-images.githubusercontent.com/8929314/34161029-7d7ec046-e4cf-11e7-91e3-fcff9bad52b4.png)

What about doing these paper style ?

**Comment by Rach-Coster** [comment]
Anyone working on this cause if we have the art I am keen to implement.

**Comment by TotomInc** [comment]
What do you mean by art @Rach-Coster? Some graphical assets? A preview of what people expect as a switch component in papercss?

**Comment by rhyneav** [comment]
I saw [this codepen](https://codepen.io/AllThingsSmitty/pen/EbJNXY) on Reddit and liked its implementation. Just needs a little more paper-y feel.
![peek 2017-12-27 11-50](https://user-images.githubusercontent.com/13633775/34387470-583d5648-eafc-11e7-8260-c45a87067302.gif)

**Comment by antoninadert** [comment]
@rhyneav  This looks good, but what about having 2 labels of extremely different size? -> won't look good.

As well I believe this implementation looks more like a toggle button than a switch (even if they are functionally similar, as for checkboxes)

Maybe have both the 'toggle button' flavor and the 'switch' flavor ? 

I believe a switch is better structured with a separate label and then the switch. Usual alignment would be left-aligned labels and right-aligned switchs, but it should be easily customizable.

A switch is good for a list of settings in a menu, a toggle is good to make an action, why not have both ?

**Comment by antoninadert** [comment]
@rhyneav I believe you should go with your version of the switch since you are almost there. My arguments were not against your point. I believe it is already good to have something like your codepen example

**Comment by rhyneav** [comment]
Fixed and deployed in version 1.7.0!
