### ISSUE TITLE
PaperCSS 1.4 Released

### ISSUE THREAD

**Issue by rhyneav** [papercss/papercss#128]
Featuring the [rewrite to SCSS](https://github.com/papercss/papercss/pull/122), brand spanking [new documentation site](https://github.com/papercss/papercss/pull/82), and [collapsibles](https://github.com/papercss/papercss/pull/113)! This was a huge release, and thank you to everyone involved! 

Check out the [release notes](https://github.com/papercss/papercss/releases/tag/v1.4.0), and the new [getpapercss.com](https://www.getpapercss.com/)!

**Comment by koester** [comment]
Best release the year 🎉  🍾

**Comment by tan-ahmed** [comment]
amazing, great work all!! 

how are you feeling about SASS vs Less?

**Comment by rhyneav** [comment]
I'm mostly used to Less, but they're so similar that it's not too challenging to figure out the differences @tan-ahmed. Overall, I like SASS mostly because of the bigger community around it :)
