### ISSUE TITLE
Close modals when clicking out of the modal

### ISSUE THREAD

**Issue by ayip001** [papercss/papercss#129]
I think modals should be closed when clicking outside of the modal.
Current behavior:
Clicking on the gray area outside of the modal box does nothing.
Improved behavior:
Clicking on the gray area outside of the modal box closes the modal.
Improved behavior demonstration from w3schools:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_modal

**Comment by koester** [comment]
I think we wanted to keep it Css only. Closing the modal when clicked outside is not possible with just css, AFAIK.

**Comment by TotomInc** [comment]
I haven't seen of modals are made, but can't we trick it by creating a "fake close button" on the backdrop? This way when we click outside of the modals, it act like the closing button.

**Comment by ayip001** [comment]
Found a CodePen as @TotomInc described
[Pure CSS modal box
A Pen By Kasper Mikiewicz](https://codepen.io/Idered/pen/vytkH)

**Comment by rhyneav** [comment]
Very cool! I did not realize that was possible.

**Comment by rhyneav** [comment]
Thank you @koester for adding this! It's been merged into develop and will be available in the next release. 

Feel free to check out the develop branch and build the CSS if you'd like this feature now.
