### ISSUE TITLE
gulp-sass should be moved into dependencies

### ISSUE THREAD

**Issue by sullivanpt** [papercss/papercss#132]
Trying npm install papercss@1.4.0 (on Windows 10) and I'm getting this error.  I think the simple fix is to move gulp-sass from devDependencies to dependencies. Also some additional changes related to hugo/docs are needed, detailed below.

```
> papercss@1.4.0 postinstall C:\Source\my-project\node_modules\papercss
> gulp build

module.js:538
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
```

And after moving gulp-sass into dependencies there are more postinstall errors trying to build the hugo docs.   I could work through these, but as the docs aren't that useful in the dependency use case, it's probably better to just not build the docs as part of the postinstall 'gulp build' task.  Here's the error after the very lengthy hugo-bin install

```
> papercss@1.4.0 postinstall C:\SourcePts\my-project\node_modules\papercss
> gulp build

[14:54:06] Using gulpfile C:\SourcePts\my-project\node_modules\papercss\gulpfile.js
[14:54:06] Starting 'sass'...
[14:54:06] Finished 'sass' after 11 ms
[14:54:06] Starting 'minify-css'...
[14:54:06] Starting 'hugo-build'...
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Config File "config" Not Found in "[C:\\SourcePts\\my-project\\node_modules\\papercss\\docs]")
```

**Comment by sullivanpt** [comment]
Hi, although it's not a blocker, would you consider releasing a patch with this fix in the near future?

**Comment by rhyneav** [comment]
I think that's a good idea @sullivanpt. A fix for modals has also been introduced so a patch release with both would be beneficial. I'll get that together this weekend :)

**Comment by rhyneav** [comment]
@sullivanpt [version 1.4.1](https://github.com/papercss/papercss/releases/tag/v1.4.1) is now available on Github, NPM, and the CDN. Hope this helps!
