### ISSUE TITLE
CSS Modal Conflicting with Bootstrap 4 Beta 3 Css

### ISSUE THREAD

**Issue by y471n** [papercss/papercss#138]
On using Bootstrap 4 beta 3 version, Modal does not work.

**Comment by rhyneav** [comment]
Could you please provide some additional details or screenshots by what you mean? Since PaperCSS is implicit with a lot of its styles, it can sometimes not play nice with other frameworks.

**Comment by TotomInc** [comment]
It's highly recommended to not use any other CSS framework while using PaperCSS. It can lead to some incompatibilities becuase of the use of shared classes. Also Bootstrap modals use JS while PaperCSS use pure css, which can also lead to bugs.

**Comment by koester** [comment]
Could you create a codepen with the modal code you're trying to implement and post the link here? I'd like to see the exact cause of the bug, although I think @TotomInc and @rhyneav are correct.

Should we add a paragraph about this to the Readme to avoid confusion?

**Comment by rhyneav** [comment]
That’s a good idea @koester. It doesn’t explicitly say “doesn’t play nice with others” anywhere in the docs.
