### ISSUE TITLE
Bootswatch theme Sketchy is using papercss?

### ISSUE THREAD

**Issue by TotomInc** [papercss/papercss#139]
So, I was browsing some Bootstrap themes on [bootswatch](https://bootswatch.com) and I see the [Sketchy](https://bootswatch.com/sketchy/) theme which looks like PaperCSS. Can someone confirm this?

If true, I find this really amazing to see this framework implemented in a very popular bootstrap theme creator.

**Comment by afzalsayed96** [comment]
![image](https://user-images.githubusercontent.com/14029371/36555316-9c08986c-1827-11e8-88e0-fc52a601dda7.png)
There's no mention of it being based on PaperCSS anywhere though

**Comment by rhyneav** [comment]
Wow, that is really cool! Really like the fonts and colors used in Sketchy.

**Comment by TotomInc** [comment]
So I'm not really into licenses, but is it required to put a mention for papercss? Looks like the style is heavily based on papercss.

**Comment by rhyneav** [comment]
Same here @TotomInc. But since it just looks similar and not actually using PaperCSS, I don't believe any attribution is necessary. I'm just happy to see more sites that look hand drawn! :)

**Comment by TotomInc** [comment]
IMO it looks like he just ripped some code from papercss, because I have the feeling that buttons (e.g.) are 100% the same in terms of border and border-radius. The only thing that change are the colors used.

But if it's okay for you, we can close this issue. I wanted to know if he needed to put a mention for papercss (at least for the inspiration... 😕 )
