### ISSUE TITLE
Review padding

### ISSUE THREAD

**Issue by Rahmon** [papercss/papercss#141]
The padding property is a shorthand property to set the four padding properties (top, right, bottom, and left) in one declaration. 

In some cases, the padding has two equal values and could be use just a value. For example, in src/components/_buttons.scss:
`padding: .75rem .75rem;`

It's could be change to:
`padding: .75rem`

This inconsistency occurs in the files below:
- papercss/src/components/_buttons.scss
  - [ ] [Line 13](https://github.com/papercss/papercss/blob/79a4875abecbe6ba5c1ffbc79e7d694e22631f70/src/components/_buttons.scss#L13)
  - [ ] [Line 27](https://github.com/papercss/papercss/blob/79a4875abecbe6ba5c1ffbc79e7d694e22631f70/src/components/_buttons.scss#L27)
- papercss/src/components/_tabs.scss
  - [ ] [Line 25](https://github.com/papercss/papercss/blob/79a4875abecbe6ba5c1ffbc79e7d694e22631f70/src/components/_tabs.scss#L25)
- papercss/src/components/_accordion.scss
  - [ ] [Line 30](https://github.com/papercss/papercss/blob/79a4875abecbe6ba5c1ffbc79e7d694e22631f70/src/components/_accordion.scss#L30)
  - [ ] [Line 38](https://github.com/papercss/papercss/blob/79a4875abecbe6ba5c1ffbc79e7d694e22631f70/src/components/_accordion.scss#L38)
- papercss/src/components/_forms.scss
  - [ ] [Line 11](https://github.com/papercss/papercss/blob/79a4875abecbe6ba5c1ffbc79e7d694e22631f70/src/components/_forms.scss#L11)

**Comment by TotomInc** [comment]
The `padding` could be changed to a variable for better consistency, this wil avoid further inconsistencies when implementing new components.

**Comment by TotomInc** [comment]
Looks like the inconsistency have been fixed some day, closing this issue.
