### ISSUE TITLE
Making it a full-fledged HTML, CSS, and JS Library

### ISSUE THREAD

**Issue by hacu9** [papercss/papercss#143]
Could it be possible to make it involve JS (in a different repo perhaps) and make this awesome library even easier to use for big projects

**Comment by rhyneav** [comment]
A couple people have started on integrating PaperCSS with JavaScript frameworks as found on the [organization page](https://github.com/papercss). However, PaperCSS will remain a CSS framework. 

Are there any features you'd like to see added that would require JS? Some of the fun is trying keep features within the CSS constraint.
