### ISSUE TITLE
Let text input box and select box have same height

### ISSUE THREAD

**Issue by jeet-parekh** [papercss/papercss#148]
Currently the text input box and select box heights are not same. It looks inconsistent because of that.

![Inputs](https://user-images.githubusercontent.com/12874561/39044960-4195d5d4-44af-11e8-8b56-e2c106407a9e.PNG)

Would it be possible to make them have same height?

**Comment by rhyneav** [comment]
Hmm, is this another Firefox issue? I agree that the inconsistent input heights is not a good look.

On Chrome, both inputs are 47px tall

![image](https://user-images.githubusercontent.com/13633775/39052469-138c3550-447a-11e8-938f-09b3534a9833.png)

**Comment by kubami9** [comment]
Beginner here, is it free to take? 😅

**Comment by rhyneav** [comment]
All yours @kubami9!

**Comment by rhyneav** [comment]
Fixed and deployed in 1.7.0!
