### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by Youngestdev** [papercss/papercss#153]
Hi, the dependencies for `papercss` are prone to attacks. It'll be nice if the dependencies are updated to their latest version to reduce the risks of attacks on website using the node module.

**Comment by rhyneav** [comment]
I looked through [the dependencies](https://github.com/papercss/papercss/network/dependencies) and did not see any vulnerabilities at a quick glance. Where there any specific dependencies that you saw are vulnerable?

**Comment by TotomInc** [comment]
There are a lot of dependencies prone to attacks, I'm working on it.
