### ISSUE TITLE
Some components are not optimized for integration with third-parties frameworks

### ISSUE THREAD

**Issue by TotomInc** [papercss/papercss#172]
I'm currently working on the vue-papercss integration and I realized that some components are not friendly with frameworks integration.

For example, the [collapsible component](https://www.getpapercss.com/docs/components/collapsible/) styling relies on the `label` and `input` tags. IMO, it should instead relies on classes, what do you think @rhyneav?

[Relevant lines for the collapsible component.](https://github.com/papercss/papercss/blob/03df3ea6075bbeec3b0d74ee88ef8ea86278e44d/src/components/_accordion.scss#L20-L48)

**Comment by rhyneav** [comment]
I agree with your point about each component including its dependencies at the top of the file. It will certainly help with seeing the exact dependencies. 

While changing the label and input tags with classes would be more semantically correct, it would have to be a breaking change. Which could lead us to... PaperCSS 2.0.0! What do you think of us looking through for more of these situations and start heading for a v2 with a bunch of cleanup and breaking changes taken care of?

**Comment by TotomInc** [comment]
Heading to a v2 branch will be great, I have done the major stuff on vue-papercss and can now focus more on papercss.

**Comment by koester** [comment]
Good idea about the import structure

And I get your point about classes instead of `label` or `input` tags, but my concern here is that this was what made papercss the less formal CSS framework. Maybe we need to discuss this in detail and see how we can tackle this problem, but either way that would be a major update.

**Comment by TotomInc** [comment]
@koester so using a base file and having encapsulated component style seems to be the best way to do this.
