### ISSUE TITLE
provide a way let developers change font path in scss

### ISSUE THREAD

**Issue by bung87** [papercss/papercss#191]
in case developers want using another cdn or serve font on own server or embed in application

**Comment by ChocolateLoverRaj** [comment]
I'm don't know much about scss, or if you can have conditional imports, but I know there is probably a way, since the souce scss files can be changed to build a modified `paper.css` file. Maybe @rhyneav can help.

**Comment by rhyne-vetcove** [comment]
I think think this would be a great addition. It could be as simple as just adding in a `$font-src` variable and if that's set then we won't use the automatic `@import` from Google fonts? A PR would be very welcomed for this if anyone has any ideas!

**Comment by rhyneav** [comment]
I think think this would be a great addition. It could be as simple as just adding in a `$font-src` variable and if that's set then we won't use the automatic `@import` from Google fonts? A PR would be very welcomed for this if anyone has any ideas!
