### ISSUE TITLE
-- becomes – inside of code block

### ISSUE THREAD

**Issue by obuchmann-pc-web** [papercss/papercss#197]
First seen on https://www.getpapercss.com/ in the code block `npm install papercss –save`.

**Comment by rhyneav** [comment]
Ah yes, a fix has been merged in for that, but I need to deploy the updated docs. Thank you for the reminder, I'll close this issue after the deploy.

**Comment by koester** [comment]
@rhyneav can this be closed now? 😅

**Comment by rhyneav** [comment]
Whoops! Yes, this should be okay now.
