### ISSUE TITLE
Google Fonts?

### ISSUE THREAD

**Issue by illupino** [papercss/papercss#201]
Does papercss use any google fonts or anything coming from an external source? if so, How can I upload and link the fonts on my webserver so to avoid google fonts calling google?

**Comment by koester** [comment]
We import [Patrick Hand SC](https://fonts.google.com/specimen/Patrick+Hand+SC) and [Neucha ](https://fonts.google.com/specimen/Neucha) from Google Fonts here:
https://github.com/papercss/papercss/blob/50dc605b36017812bc8261ebc88f30003a0848a9/src/core/_config.scss#L6

And define the font settings here:
https://github.com/papercss/papercss/blob/50dc605b36017812bc8261ebc88f30003a0848a9/src/core/_config.scss#L64-L68

On how to self host the fonts there are plenty of articles and tools to help you out there.
