### ISSUE TITLE
Tabs content position on the right instead of below the tabs

### ISSUE THREAD

**Issue by bellons91** [papercss/papercss#202]
Hi, 
I have troubles using the Tabs component, because it renders the content on the right of the tabs instead of below as in the documentation.

Here's the HTML
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://unpkg.com/papercss@1.6.1/dist/paper.min.css">
    <title>Document</title>
</head>

<body>
    <div class="paper container">

        <div class="row flex-spaces tabs">
            <input id="tab1" type="radio" name="tabs" checked>
            <label for="tab1">Tab 1</label>

            <input id="tab2" type="radio" name="tabs">
            <label for="tab2">Tab 2</label>

            <input id="tab3" type="radio" name="tabs">
            <label for="tab3">Tab 3</label>

            <input id="tab4" type="radio" name="tabs">
            <label for="tab4">Tab 4</label>

            <div class="content" id="content1">
                <p>
                    Bacon ipsum dolor sit amet beef venison beef ribs kielbasa...
                </p>
                <p>
                    Brisket meatball turkey short loin boudin leberkas meatloaf...
                </p>
            </div>
            <div class="content" id="content2">
                <p>
                    Bacon ipsum dolor sit amet landjaeger sausage brisket...
                </p>
            </div>
            <div class="content" id="content3">
                <p>
                    Bacon ipsum dolor sit amet beef venison beef ribs kielbasa...
                </p>
                <p>
                    Brisket meatball turkey short loin boudin leberkas meatloaf...
                </p>
            </div>
            <div class="content" id="content4">
                <p>
                    Bacon ipsum dolor sit amet landjaeger sausage brisket...
                </p>
            </div>
        </div>

    </div>
</body>

</html>
```

I've copy-pasted the examples from the [tabs page](https://www.getpapercss.com/docs/components/tabs/) and the [homepage](https://www.getpapercss.com/)

The result I get has the content of the tabs on the right of the labels
![image](https://user-images.githubusercontent.com/6106586/86514546-4f298a80-be13-11ea-8e04-4a68dde61707.png)

**Comment by koester** [comment]
Thank you for reporting this bug.

I've looked into this and it seems to be a problem on larger screens, but there is an easy fix for this.

To the `.tabs .content` class just add: `flex-basis: 100%;`.
```diff
 .content { 
   display: none; 
   padding: 0.75rem 0 0;
+  flex-basis: 100%;
 } 
```

I will probably not be able to fix this myself before the end of the week, so If you want to do it yourself feel free to open up a PR with a fix.

In the source we would need to add `flex-basis: 100%;` here: https://github.com/papercss/papercss/blob/dd1182f9136150b255b6df1750328064f48a61c5/src/components/_tabs.scss#L2-L5

**Comment by bellons91** [comment]
Ok then, I'll work on it (also, it will be my first ever contribution to an open source project)

**Comment by bellons91** [comment]
Sorry, I'm not able to run the project (or better, to install all the dependencies). So I give up with this issue and I'll wait for the next release...
