### ISSUE TITLE
Forms into a modal not working on electron but in a normal browser yes

### ISSUE THREAD

**Issue by defaultuser001** [papercss/papercss#209]
With normal browser like google chrome, modals works correctly, but in electron 9.1.2 don't work, it shows a simple blank square

**Comment by rhyneav** [comment]
Hey there! Sorry to hear that. Could you please provide a screenshot of what your seeing? That's certainly strange that Chrome and Electron are showing different things.

**Comment by defaultuser001** [comment]
Thanks for response!

i'm running electron on Linux Deepin (Debian). I'll test on windows 10 and write here if it works or no
 
Electron without modal:
![DeepinScreenshot_Seleccionar área_20200808093310](https://user-images.githubusercontent.com/58643218/89710553-a236b600-d95a-11ea-938b-019059d38890.png)

Electron with modal:
![DeepinScreenshot_Seleccionar área_20200808093320](https://user-images.githubusercontent.com/58643218/89710558-b11d6880-d95a-11ea-8ba8-96e38a2e33fd.png)

Chrome 78 without modal
![DeepinScreenshot_Seleccionar área_20200808093510](https://user-images.githubusercontent.com/58643218/89710572-bc709400-d95a-11ea-86be-ebfe0cbd5baf.png)

Chrome 78 with modal
![DeepinScreenshot_Seleccionar área_20200808094009](https://user-images.githubusercontent.com/58643218/89710628-2be68380-d95b-11ea-99a8-64a7d1da7e39.png)

Electron Project (in public folder):
https://github.com/defaultuser001/NumericCoder/tree/master/desktop

Official webapp (made on React):
https://numericcoder.netlify.app/

It's strange, electron works on chromiun. If it my fault with electron configs or another thing then sorry about that

PaperCSS is beautiful <3

**Comment by defaultuser001** [comment]
with windows 10 it's the same but more smooth and better lol

**Comment by defaultuser001** [comment]
Ok, it's solved, comment all of a javascript file and modal works

**Comment by rhyneav** [comment]
Awesome! Glad it’s working for you now!
