### ISSUE TITLE
Styling input range (slider)

### ISSUE THREAD

**Issue by Benbb96** [papercss/papercss#210]
Hi,

First of all, thanks for this beautiful framework!
I'm using it for a part of my website and it's looking really nice 😃 

I'm wondering about changing a number input to a range one (a slider) and I've seen it's not currently formatted into the Paper style.
_How hard would it be to customise it?_

**Comment by rhyneav** [comment]
That's awesome! We don't yet have any styles for range sliders in the library, but a PR would be very welcome! As for how hard that would be, I'm not too sure. Overriding the button looks to be [well supported ](https://www.w3schools.com/howto/howto_js_rangeslider.asp), and overriding the line to slide on will likely require some pseudo elements. All should be doable though!

**Comment by rhyneav** [comment]
Deployed in `v1.8.0`!
