### ISSUE TITLE
Security issue with old gulp-clean-css version

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [papercss/papercss#214]
## The security issue
I got a [dependabot alert](https://github.com/ChocolateLoverRaj/canvideo/network/alert/package-lock.json/clean-css/open) saying that clean-css has a minor security issue. Papercss depends on gulp-clean-css, which depends on clean-css. gulp-clean-css [updated clean-css](https://github.com/scniro/gulp-clean-css/issues/57)  in their `package.json` file. This was released in gulp-clean-css [version 3.9.3](https://github.com/scniro/gulp-clean-css/releases/tag/3.9.3).

## What papercss should do
Papercss should update their dependencies in `package.json` so that it uses at least gulp-clean-css version 3.9.3. That way there won't be a clean-css security issue.

## Can I make a pull request
I'm making this issue to ask people at papercss if they are okay with updating gulp-clean-css or let me make a pull request doing that.

**Comment by rhyne-vetcove** [comment]
Hi there! Yes please, a PR would be very welcome for this!

**Comment by rhyneav** [comment]
Hi there! Yes please, a PR would be very welcome for this!

**Comment by ChocolateLoverRaj** [comment]
Ok, thanks. I'll make a pull request.

**Comment by ChocolateLoverRaj** [comment]
What version of gulp-clean-css should papercss use? It should be at least 3.9.3, but should I just do `npm update gulp-clean-css` and just use the latest version?
