### ISSUE TITLE
No source code in NPM

### ISSUE THREAD

**Issue by PaulMaly** [papercss/papercss#227]
Hi! Seems in the latest version source code (scss) doesn't ship anymore via NPM. Only `dist` folder with output css present in node_modules. Is it an issue or intent?

**Comment by TotomInc** [comment]
It is intended, the source-code is not shipped anymore as this should be the right-way to package CSS lib/frameworks.

For more details, take a look at https://github.com/papercss/papercss/issues/216 and https://github.com/papercss/papercss/pull/219.

**Comment by PaulMaly** [comment]
Ah, it's really sad ((( Without source code, we can't optimize output css for the specific applications. It worked so cool before. 

Also, seems README should be updated - this statement is confusing now: `You can also play with original, source files, written in SCSS, in src/.`

**Comment by PaulMaly** [comment]
```
TL:DR: the old behavior was that the user compiled the framework while doing an npm install (which is very bad). Now that we migrated our build-tools, the build is done on our end and we serve it in the /dist folder.
```
I believe you can combine both things, you can ship /dist and /src together. Default behavior could be a compiled output, but low-level developers still will have access to source code to add it in their own bundler pipeline.

**Comment by rhyneav** [comment]
Hey! Sorry about that, I honestly didn’t realize it was removed. I think we want to include both the compiled CSS and the source SCSS. The goal of the change was that we don't want the person installing PaperCSS to need to compile it on install. I’ll add it back in (today hopefully) since removing the SCSS would have been a breaking change.

**Comment by TotomInc** [comment]
I totally agree with all of your answers.

There are no big deals if we add back the source-code, as we will ship both `/dist` and `/src`.

- `/dist` is built by the PaperCSS team before a release. It's the result of compiled SCSS and is what will be imported by default by most web-apps (if you don't need to personalize PaperCSS) and some CDNs.

- `/src` can be used in a way to customize PaperCSS and creating the build themselves (ie. tweaking some variables and creating their own build-tool around PaperCSS `/src` folder). Including this folder **will not affect the bundle-size** of a project which relies on PaperCSS. I see the `/src` folder as an optional way to personalize PaperCSS without impacting others which only uses the `/dist`.

**Comment by rhyneav** [comment]
Sounds perfect! I just released `v1.8.1` with the `src` folder added back. @PaulMaly please let me know if anything else is missing there.

**Comment by PaulMaly** [comment]
@rhyneav @TotomInc Thank you guys for speed ))) I believe it's a good solution in general. 

I also found the issue with output css you shipped in /dist. 

Check this out, pls: https://github.com/papercss/papercss/blob/master/dist/paper.css#L1409 

It's definitely not correct css output I think.

**Comment by rhyneav** [comment]
Thank you for the heads up, opened #228 to track this!
