### ISSUE TITLE
Update docs for new build.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [papercss/papercss#229]
Right now the `customize` section of the docs is outdated, and it references `gulp build`. Since gulp is no longer used, we should update the docs to say `npm run build` or `npm run css:build`, and explain what `css:build`, `hugo:build`, and `build` do. I will be happy to make a pull request with these changes.

**Comment by ChocolateLoverRaj** [comment]
`readme.md#contributing` and `contributing.md` also are outdated. I will also update those.

**Comment by rhyneav** [comment]
Sounds great, thank you!
