### ISSUE TITLE
how to support Chinese characters

### ISSUE THREAD

**Issue by turtlekey** [papercss/papercss#237]
This repo is amazing, but it seems that Chinese character isn't  supported. So how to support it, or it is coming?

**Comment by rhyneav** [comment]
Hi @turtlekey, you'll want to override the `$font-src`, `$header-font`, and `$body-font` variables to be a font that better supports Chinese characters. There's currently an open issue, #233, on adding some docs to cover this use case and other common customizations.

**Comment by turtlekey** [comment]
Thanks for reply. I have found that the font([站酷快乐体](https://www.zcool.com.cn/special/zcoolfonts/)) is very suitable for the style  of PAPERCSS in the case for Chinese, and most importantly, this font can be used freely ( free beer) both individually and commercially.

**Comment by TotomInc** [comment]
@turtlekey thanks for taking the time to write your explanation. I'm sure it will help users that encounter the same problem when coming from Google. 😛
