### ISSUE TITLE
Enable "font-display: swap " to avoid showing invisible text

### ISSUE THREAD

**Issue by lousolverson** [papercss/papercss#260]
In order to improve the pagespeed score, I tried a few change in the _config.scss file:
replace $font-src: 'https://fonts.googleapis.com/css?family=Neucha|Patrick+Hand+SC' !default;
by $font-src: 'https://fonts.googleapis.com/css?family=Neucha|Patrick+Hand+SC&display=swap' !default;
With this the FOIT  disappeared and the font-display audit succeeded.

**Comment by koester** [comment]
Thanks for noticing this. Feel free to open a new PR with your proposed change.
