### ISSUE TITLE
Stylelint Error

### ISSUE THREAD

**Issue by gjssss** [papercss/papercss#278]
Hello! I'm coding in WIN11.
I forked the repo and changed a little code.
But when I run `npm run stylelint`, There is an Error
```
Error: No files matching the pattern "'src/**/*.scss'" were found.
    at ***\papercss\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

By the way, when I run `npm start`, It said there no file named `hugo.exe` in `node_modules/hugo-bin/vendor/hugo.exe`(This is not the original words), so I got the `hugo.exe 0.74.3` , put it in that place and fixed.

**Comment by gjssss** [comment]
I change the `package.json`
from
```
"stylelint": "stylelint 'src/**/*.scss'"
```
to
```
"stylelint": "stylelint \"src/**/*.scss\""
```
Now, It can work!
I don't know if it's because I'm using Windows

**Comment by rhyneav** [comment]
Thank you for the catch, it might be windows specific. A PR would be well received here to help fix this!

**Comment by gjssss** [comment]
Thank you!
