### ISSUE TITLE
Breaking change in Sass: Color Units

### ISSUE THREAD

**Issue by almibarss** [papercss/papercss#281]
I just stumbled upon this cute deprecation warning when compiling my sass files today:

```
DEPRECATION WARNING: $saturation: Passing a number without unit % (0) is deprecated.

To preserve current behavior: $saturation * 1%

   ╷
68 │ $shadow-color-regular: hsla(0, 0, 0%, 0.2) !default;
   │                        ^^^^^^^^^^^^^^^^^^^
   ╵
    papercss/src/core/_config.scss 68:24  @use
    placeholder.scss 2:1                  root stylesheet
```

It seems there are some [breaking changes in the spec](https://sass-lang.com/documentation/breaking-changes/color-units):

> In CSS, saturation and lightness parameters always require % units and hue parameters allow any angle unit. Sass has historically ignored units for these functions. We're in the process of changing that.

**Comment by rhyneav** [comment]
Fixed in #282!
