### ISSUE TITLE
unexpected line skip with <p> inside <li>

### ISSUE THREAD

**Issue by gvwilson** [papercss/papercss#292]
Thank you for PaperCSS - I just converted my personal site to use it (https://third-bit.com/) and it looks great except for one thing that I don't know enough CSS to debug. I am using Jekyll + Kramdown to convert Markdown to HTML; if there is _not_ a blank line between list items, like this:

```
-   first item
-   second item
-   third item
```

then the generated HTML is:

```
<ul>
<li>first item</li>
<li>second item</li>
<li>third item</li>
</ul>
```

which renders as expected. However, if I put blank lines between list items to make them more readable (some of them are quite long) then Jekyll + Kramdown inserts a `<p>` inside each `<li>`, so:

```
-   first item

-   second item

-   third item
```

becomes:

```
<ul>
<li><p>first item</p></li>
<li><p>second item</p></li>
<li><p>third item</p></li>
</ul>
```

PaperCSS puts a blank line between the list item marker and the start of the text in this case. The result can be seen in e.g. the bottom half of https://third-bit.com/2022/12/29/the-fourth-tradition/:

<img width="980" alt="Screenshot 2023-01-16 at 7 19 12 AM" src="https://user-images.githubusercontent.com/911566/212676704-3a047617-1cd8-4572-877a-6b9fce72ebe2.png">

What is the cleanest/simplest way to add something on top of PaperCSS to eliminate this undesired spacing?

**Comment by mstimberg** [comment]
I don't know much about PaperCSS (came here via your post on Mastodon), but if you never need "proper" paragraphs within `<li>` elements, then you should be able to make such paragraphs into inline elements via the following in your css file that you apply on top of PaperCSS:
```css
li p {
  display: inline;
}
```

**Comment by gvwilson** [comment]
Thanks - that fixes the problem for one paragraph in a list item, but not for:

```
-   first item is a full paragraph

-   second item is two paragraphs

    this is the second of those paragraphs

-   third item is just one paragraph again
```

I'll experiment with `:first-child` and the like to see if that'll take care of it - thank you.

**Comment by mstimberg** [comment]
Not sure whether this is a good idea, but you could also force line breaks between paragraphs with this (from [here](https://css-tricks.com/injecting-line-break/)):
```css
li p::after
{
  content: "";
  display: block;
}
```

**Comment by Brandon-Schefstad** [comment]
@gvwilson Pushing up a PR for this change. 

![image](https://user-images.githubusercontent.com/63316287/214730957-f0821ee7-db09-486e-a914-f524ebad46e4.png)
![image](https://user-images.githubusercontent.com/63316287/214730970-f0f7df2e-e796-4955-859b-f29f35ac3218.png)

Let me know if this is the behavior you're expecting!

**Comment by gvwilson** [comment]
thank you

**Comment by Brandon-Schefstad** [comment]
There is also this change if you want separated paragraphs:
![image](https://user-images.githubusercontent.com/63316287/214734015-005e89a1-6110-49e6-9f0a-3431b90423bc.png)

![image](https://user-images.githubusercontent.com/63316287/214734061-1b430b4c-4ec9-4034-bca2-b89a4623fcdb.png)
