### ISSUE TITLE
Tutorials and examples

### ISSUE THREAD

**Issue by Fraham** [papercss/papercss#36]
I think we should open up the github wiki so we can create some tutorials and examples for anyone how is trying to use PapaperCSS will be able to quickly implement the framework

**Comment by rhyneav** [comment]
100% yes @Fraham. It'd also be nice to have a demo page or two to link to on the main papercss page. Just to show what it might look like in the wild.

**Comment by amanbayev** [comment]
@Fraham @rhyneav also would be nice to show the navigation (navbar/sidebar/topbar/?) which was intented to be used with Paper CSS.

**Comment by TotomInc** [comment]
We can add examples/templates like Bootstrap have done: "starter template", "grid system", "dashboard" and other things like that. It's important for people to quickly have an overview of what the framework is capable when everything is put together in a **real-world app**, and I think Bootstrap have done this the right way.

**Comment by rhyneav** [comment]
Bootstrap's docs are stellar @TotomInc, totally agree there. Would it be best to have these examples on the site (at something like getpapercss.com/examples/) or would using the Github project wiki be best as @Fraham mentioned?

**Comment by TotomInc** [comment]
It would be better to have them on new pages, sure it will take some time to build examples but it's really worth it. It really make sense for someone discovering the framework, he wants to see what this framework is capable so he can view an example layout.

**Comment by amanbayev** [comment]
I suggest we build some SPA with demo like in Bootstrap.

**Comment by TotomInc** [comment]
Well as a SPA we can build the docs using PaperCSS, it would be a great example itself. I have a preference for vue.js as a JS framework.

**Comment by amanbayev** [comment]
@TotomInc I am only able to build ReactJS version. Perhaps it would be a great practice to try VueJS for a change, but not sure that you can rely on quality.

**Comment by TotomInc** [comment]
We should give a try to vue.js, it's great for small and medium-sized apps.

**Comment by amanbayev** [comment]
@TotomInc bought Vue course on Udemy. You were the last push I needed (everyone around me seems to be excited about this technology) to get started on Vue.

**Comment by amanbayev** [comment]
Please take a look at SPA built with ReactJS and Meteor:
http://startupzone.kz/

source is available at:
https://github.com/amanbayev/papercss-meteor-react-tutorial

to run you will need to install meteor from https://www.meteor.com/
once you checkout the project just run
```
meteor npm i --save
```
then
```
meteor
```

**Comment by TotomInc** [comment]
This is good but it needs more customization to be an official documentation SPA. Something like a static navbar with all useful links, a better sidebar containing the summary (with dropdowns?). Otherwise, great work!

**Comment by amanbayev** [comment]
@TotomInc thanks for Feedback. Yeah, right now it is all copy-paste from official (current) docs of PaperCSS.
Static navbar - I dont think we have a way to do it yet. All I did was used Summary section as is.
Perhaps someone could help me with official tutorial ideas.

**Comment by Kenan7** [comment]
As you write tutorial, add it to crowdin so i can translate it to Azerbaijani and Turkish and reach a lot of person who wants to learn!

**Comment by DarkPaladinUHC** [comment]
I would like to work on this, I think that Vue is a great idea! Would we add it to this repository or a separate one?

**Comment by TotomInc** [comment]
Hi @DarkPaladinUHC, you are a bit too late they started to write new docs with examples using Hugo. We have a react and a vuejs version of this framework, which you can find at papercss/vuejs-papercss. I'm in charge of the vuejs version, if you would like to contribute we can add you in the vuejs team and talk about it.

**Comment by DarkPaladinUHC** [comment]
@TotomInc Alright, I guess I didn't see it. Sorry

**Comment by DarkPaladinUHC** [comment]
@TotomInc Is the vuejs team for making components for each of the features?

**Comment by TotomInc** [comment]
Yep @DarkPaladinUHC the vuejs team is making components for each feature available in the original papercss. [You can look at the actual progression here](https://github.com/papercss/vuejs-papercss), before releasing a 1.0.0 of this repo, we need to get all features from papercss.

**Comment by TotomInc** [comment]
Since we got a Hugo version for docs and example, I assume I can close this issue @rhyneav.
