### ISSUE TITLE
[not a real issue - presentation issue] github repo presentation gif is too fast

### ISSUE THREAD

**Issue by mnemosdev** [papercss/papercss#46]
The presentation gif to showcase the documentation is too flashy and fast, which could be annoying but most of all, it doesn't show much! I think it would be a better choice to have it a little bit slower, but that's just my two cents, love u <3

**Comment by talandaw** [comment]
Agreed, I got to this page and was confused with all the images flashing before my eyes before I realized what the gif was supposed to be showing me.

**Comment by TotomInc** [comment]
This will be fixed once #36 get done. We will replace the fast-scrolling gif with pictures of examples layouts done with the framework.

**Comment by rhyneav** [comment]
Totally agree! It was a fast and dirty way of adding some motion to the README. Until #36 is wrapped up, I'd be happy to merge in a replacement gif that's a little less... extreme.

(and thank you for the kind words @mnemosdev <3)

**Comment by TotomInc** [comment]
Better docs are coming soon, and I will open a new issue to suggest an overhaul of the readme. I close this issue since it's only a small part of my upcoming issue.
