### ISSUE TITLE
Code for documentation is no longer maintenable

### ISSUE THREAD

**Issue by TotomInc** [papercss/papercss#48]
Having a big index.html file containing all our "examples components" with the lines of code used is not the best thing to do. It's messy and the doc can be a pain to browse for devs, but also a pain for contributors.

My solution here is to keep `/index.html` as a landing page for the framework (quick description, some pictures, link to GitHub/docs, ...).

Then all the docs will go to `/docs` where each component will get its own `.html` such as `cards.html` or `alerts.html`.

Doing this will allow us more flexible PRs (when everyone is editing the same index.html file, they have to deal with A LOT of conflicts when they want to merge). But it will also create a more structured documentation, something we should take seriously since the framework is growing a lot.

Should we use a JS framework to do this? Should we go as a SPA or go for the old-school method?

**Comment by rhyneav** [comment]
Well, the monolithic index.html file wasn't going to last forever... 

I like your strategy. Keep some links and a description on the landing page and separate out the documentation into many files. 

Going the old-school method might be a pain in terms of initial set up, but keeping a framework out of the equation would make contributing easier. Someone wouldn't need to learn React or Vue, they could just add/edit HTML. 

However, going the SPA way would let us keep things very DRY in the documentation. We could just create the sample code and the framework could create the `<code>` on the page for us. Preventing problems of keeping those `<code>` snippets consistent.

At the end of the day, I think using a SPA would be better in the long run. What are your thoughts @TotomInc?

**Comment by afzalsayed96** [comment]
I agree here with @TotomInc . It is a pain to scroll back to the top and/or find other links from the page. We gotta modularize the code and doc

**Comment by TotomInc** [comment]
I totally agree about using a SPA, it was my initial goal. What would be even better is a system like this: all the text of the docs are on this repo, written in `.md`. Then the text of this `.md` is parsed into the SPA, this will allow people that don't know the framework to contribute on the docs.

**Comment by rhyneav** [comment]
That would be perfect @TotomInc. In that case, would it be best to use a static site generator? A happy medium between both worlds?

**Comment by TotomInc** [comment]
I don't really know anything about static site generator. Are you talking about GitHub Pages generator? Help is wanted on this issue. :sos:

**Comment by rhyneav** [comment]
Haha SOS! 

I don't know if we'd want to go with the Github Pages generator, just to avoid being totally locked in to their ecosystem. Maybe something like http://www.metalsmith.io/?

Totally just guessing here, research/help is much needed here.

**Comment by MunifTanjim** [comment]
I think creating an SPA would be overkill here. Using Static Site Generator seems like a good way to go. I'll suggest [Hugo](https://gohugo.io/) for this.
If you decide to go with Hugo, I can help by developing a Hugo template with PaperCSS which will be used as the PaperCSS landing page & documentation site.

**Comment by muyaszed** [comment]
Hi, is the current index.html is serve from github ?

**Comment by TotomInc** [comment]
Yes, it is currently served from Github @muyaszed

**Comment by rhyneav** [comment]
Hugo looks like a great option for this @MunifTanjim. It looks like it's [pretty dang popular](https://www.staticgen.com/) too. 

My question is, how much overhead is required to getting Hugo installed? If someone came across PaperCSS now, all they need to do now is clone the repo, `npm install`, and `npm start` to get the docs and CSS loaded up. Would Hugo add a lot of complexity to this vs using something Node based like [Hexo](https://hexo.io/)?

**Comment by MunifTanjim** [comment]
@rhyneav 
Well, there is a binary wrapper for `hugo` on `npm` registry: [hugo-bin](https://github.com/fenneclab/hugo-bin). So, it can be added as a `package.json` dependencies.

I don't think `hugo` will add complexity. And the major plus point of Hugo is its **crazy fast** speed compared to any other static site generator.

And the contributor will only work with only Markdown files for documentation.

**Comment by rhyneav** [comment]
I'm sold! Hugo sounds like a great way to break up the monolithic index.html file.

**Comment by TotomInc** [comment]
Let's go for Hugo so! Who is charged of setting up the whole thing? I don't have any experience in this, so I'm not on it.

**Comment by MunifTanjim** [comment]
:hand: I can do this. I've experience creating templates for Hugo.

**Comment by rhyneav** [comment]
@MunifTanjim That would be amazing! Please let me know what I can do to help out.

**Comment by TotomInc** [comment]
This can be closed since it is actually done on develop branch.
