### ISSUE TITLE
What about React version of the PaperCSS?

### ISSUE THREAD

**Issue by ummahusla** [papercss/papercss#51]
Are you considering building a React version of this framework?

**Comment by amanbayev** [comment]
I'd love to participate @ummahusla

**Comment by TotomInc** [comment]
I don't think so, since we want the framework to be the most simplest without any big integration to be done. It will stay, if @rhyneav agrees, a pure CSS framework. Maybe a React version can be done by the community, but I don't think it will have its place in the official repo.

**Comment by ummahusla** [comment]
@TotomInc How about creating a GitHub organisation account, move repository there, and there we would be able to create a react version of the framework. I guess a lot of the users would pick it up and collaborate on this.

**Comment by ummahusla** [comment]
@amanbayev Good! 👍 Me too

**Comment by TotomInc** [comment]
I'm not the owner as you see, we need to involve @rhyneav in this issue!

**Comment by ummahusla** [comment]
@TotomInc Yep, I've noticed that. I'm just sharing my idea.

**Comment by rhyneav** [comment]
Hey @ummahusla what do you mean by React version? Like creating React components similar to [Reactstrap](http://reactstrap.github.io/), or building the documentation page in React?

**Comment by ummahusla** [comment]
@rhyneav Yep, my idea is to make something like `Reactstrap`.

**Comment by Kaperskyguru** [comment]
I will love to participate

**Comment by rhyneav** [comment]
Sounds like a great project! What can I do to help get things set up for you all? I have the organization, papercss on Github if you think setting up a repo there would be a good start.

**Comment by ummahusla** [comment]
@rhyneav Setting up a repo will be a good first step. Then we can start a `Project` directly in this repo. I guess the toughest point will be to setup the actual project and make it build smoothly.

**Comment by Banjerr** [comment]
@ummahusla @rhyneav @Kaperskyguru i've started "React"-ifying PaperCSS earlier today, made a new "issue" to share, but I'll share here as well. I haven't gotten everything converted over into components yet, but a decent portion has been done. I can transfer the repo over to the PaperCSS org if needed. it's also on NPM, which of course I can edit also

**Comment by rhyneav** [comment]
That sounds good @ummahusla, I'm looking into moving over this repo as well as it keeps growing.

@Banjerr, that is awesome! Since you've already done the leg work in getting set up, I can either set up the react-papercss repo in the papercss organization and let you add your changes there. Or you can transfer it over your existing repo and I can add others to a team there for you.

**Comment by Banjerr** [comment]
@rhyneav i'm up for whatever makes the most sense. 

"demo" page is up, just a simple Create React App published to GitHub pages - I think this is a good way to test functionality as new components are Reactified.

https://banjerr.github.io/React-Paper-CSS-Page/

and its published as a package on NPM as "react-paper-css", currently under my user but i can transfer this to an org or whatever makes the most sense here as well

**Comment by rhyneav** [comment]
I went ahead and created a repo on the organization page if that's okay with you @Banjerr. I've added both Yourself and @ummahusla as members to the team so far.

**Comment by rhyneav** [comment]
Link: https://github.com/papercss/react-papercss

**Comment by Banjerr** [comment]
sounds good to me @rhyneav 

I've transferred my work thus far to the org, which is at
https://github.com/papercss/react-paper-css

We can rename/delete the "duplicate", whichever is easier. I'll work on transferring over the "demo" page and setting it up on a GitHub page for the organization, also.

**Comment by ummahusla** [comment]
@Banjerr @rhyneav good job guys 👍

**Comment by afzalsayed96** [comment]
I would also like to contribute to the react version 👍

**Comment by ummahusla** [comment]
@afzalsayed96 I've started adding new issues to stuff we need to do. Feel free to help yourself. https://github.com/papercss/react-paper-css

**Comment by rhyneav** [comment]
Closing this now that the react repo is up and running :)
