### ISSUE TITLE
Version 1.2

### ISSUE THREAD

**Issue by rhyneav** [papercss/papercss#67]
A lot of awesome features and fixes have been added over the past couple of weeks. I think it's time to create release branch 1.2 and get ready to launch v1.2!

**Comment by rhyneav** [comment]
With #71 merged it, the [release branch](https://github.com/rhyneav/papercss/tree/release-1.2) has been created off of develop! This branch will be used to prepare the metadata and download links as well as fix any little bugs that may have popped up.

Check out the preview at https://release-1-2.getpapercss.com/

**Comment by Fraham** [comment]
Cool, some really good nice features :)

**Comment by rhyneav** [comment]
Closing because it is now released! <3
