### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by rhyneav** [papercss/papercss#70]
In addition to adding an .editorconfig (#54), adding a linter like [stylelint](https://stylelint.io/) would be beneficial in keeping contributions well styled.

**Comment by MunifTanjim** [comment]
[Prettier](https://github.com/prettier/prettier) would be a good choice for this.

**Comment by rhyneav** [comment]
Prettier looks great for this, thank you for the link!

**Comment by rhyneav** [comment]
After doing some research, it looks like Prettier is used more to auto format code, whereas a linter like [stylelint](https://stylelint.io/) is better suited for warning about inconsistent code formatting. It's also nice to have the code base now in SCSS as there are a lot more tools in this department than for LESS.

After an initial run with stylelint, it looks like a lot of style tweaks are needed :O 

![image](https://user-images.githubusercontent.com/13633775/34544124-664a6bd4-f0b2-11e7-8f10-4bd6705a9c83.png)

Code is currently being worked on in the [feature-linter](https://github.com/papercss/papercss/tree/feature-linter) branch. I'll look more into what rules should or not be used, but it should be testable with an `npm install` and `npm run stylelint`. After rules have been figured out, then going through and updating the code should be a breeze.

**Comment by rhyneav** [comment]
Added in 1.5.0 :)
