### ISSUE TITLE
Amazing work !

### ISSUE THREAD

**Issue by antoninadert** [papercss/papercss#77]
I didn't know how to contact you so thank you, this is real cool.

I believe we can add more elements like Tabs, I really like how easy it is to pick it and change it (pure CSS wins) 

Thank you

**Comment by rhyneav** [comment]
Thank you so much! I really appreciate it, and I'm sure the other contributors do too :)

PaperCSS is still in the early stages, so there are a lot more elements that can be added!

**Comment by afzalsayed96** [comment]
Added tabs in PR #84

**Comment by TotomInc** [comment]
Since #84 have been merged and introduce tabs, I close this issue. Thanks for your contribution!
