### ISSUE TITLE
Code related HTML Tags style

### ISSUE THREAD

**Issue by MunifTanjim** [papercss/papercss#80]
The general guideline for using `<code>` tags goes somewhat like this:

- `<code>` should be used for inline codes that can wrap
- `<pre><code>` should be used for block of codes that shouldn't wrap

Here's an example taken from [W3C Recommendation for HTML5](http://www.w3.org/TR/html5/grouping-content.html#the-pre-element):

```
<p>This is the <code>Panel</code> constructor:</p>
<pre><code>function Panel(element, canClose, closeHandler) {
  this.element = element;
  this.canClose = canClose;
  this.closeHandler = function () { if (closeHandler) closeHandler() };
}</code></pre>
```

Various **markdown parsers** do the exact same thing. And various **syntax highlighter** libraries styles code blocks based on that.

With the current `code` style, this is a bit broken:

![papercss-issue-code-style](https://user-images.githubusercontent.com/8050659/33222706-48dabc1e-d183-11e7-8e02-7a09bf2ced39.png)

`code` inside `pre` tag should have `background: transparent` and `color: inherit` to solve this problem:

```css
pre code {
  color: inherit;
  background: transparent;
}
```

![papercss-issue-code-style-fixed](https://user-images.githubusercontent.com/8050659/33222810-1f1a3502-d184-11e7-9a05-e2b5f6efc648.png)

**Comment by rhyneav** [comment]
Ah that makes a lot of sense. I've seen a lot of other libraries use the `<pre><code>` combination, but never fully understood why. Thank you for the links and for the help, this will definitely need to be updated. T

**Comment by Fraham** [comment]
I dont think so

**Comment by afzalsayed96** [comment]
Imo this fix can be directly added in PR #81

**Comment by MunifTanjim** [comment]
Nope, it should be a different PR. #82 is only about the documentation site.
( moreover, I'm not actually comfortable editing LESS files )
@afzalsayed96

**Comment by afzalsayed96** [comment]
Ok thanks @MunifTanjim I'll create a new PR
