### ISSUE TITLE
React PaperCSS

### ISSUE THREAD

**Issue by Banjerr** [papercss/papercss#81]
I love this! I hope you don'd mind, but i've started going through and turning some of these into React components, which can be found here 

https://github.com/Banjerr/react-paper-css

I should have them all "React"-ified soon!

**Comment by rhyneav** [comment]
I don't mind one bit, I think that is so cool! I also wanted to link #51 where some others are talking about doing the same thing.

**Comment by Banjerr** [comment]
Awesome, I actually already saw and commented there too. I've almost got the "demo" page up on GH pages

**Comment by rhyneav** [comment]
Going to go ahead and close this since it's now at https://github.com/papercss/react-paper-css
