### ISSUE TITLE
Papper Css gem for Rails

### ISSUE THREAD

**Issue by muyaszed** [papercss/papercss#86]
Hi Everyone, since there is already a #81 , I just cretaed a ruby gem to integrate Papercss to rails for whoever using erb for the front-end

Here is the gem - https://github.com/muyaszed/rails_papercss_gem
and here is the Demo - https://rails-papercss.herokuapp.com

Cheers

**Comment by rhyneav** [comment]
Very nice! Please let me know if you'd like to add it to the PaperCSS organization. You'd retain ownership, and it would help with visibility. This repo will eventually migrate that direction as well.

**Comment by muyaszed** [comment]
> Very nice! Please let me know if you'd like to add it to the PaperCSS organization. You'd retain ownership, and it would help with visibility. This repo will eventually migrate that direction as well.

Yes, that would be great

**Comment by rhyneav** [comment]
Cool! Feel free to transfer over the repo whenever you are ready :)

Thank you for creating that, it's nice to see PaperCSS expanding to the Rails world.

**Comment by muyaszed** [comment]
I tried to transfer but I get an error saying I do not have any permission to create a repo on the organization

**Comment by rhyneav** [comment]
Ah dang! I just added you as a team member, please let me know if there's any other errors!

**Comment by muyaszed** [comment]
ok done
