### ISSUE TITLE
Inline list

### ISSUE THREAD

**Issue by muyaszed** [papercss/papercss#87]
Hi I would like to add inline list feature in this framework. It is just very simple add on that is useful for menu or other things. Below is the example from my branch

![screen shot 2017-11-27 at 8 14 29 pm](https://user-images.githubusercontent.com/10081727/33287251-02635028-d3b0-11e7-8013-31130c954585.png)

**Comment by Fraham** [comment]
If you make a pull request from your branch to the develop branch then we should be able to see your less code and hopefully get it merged into the project

**Comment by afzalsayed96** [comment]
Could be closed now?

**Comment by muyaszed** [comment]
Yes
