### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Fraham** [papercss/papercss#92]
I think it would be nice to have better communication in the organisation. I would suggest using slack so we can keep track of projects and developments, it also works nicely with web hooks.

**Comment by afzalsayed96** [comment]
I second that

**Comment by rhyneav** [comment]
I'm open to using Slack, but would like to keep communication as open as possible. I'm a Slack novice, is it possible to have a public channel?

**Comment by TotomInc** [comment]
I would agree on a Slack channel, very useful.

**Comment by Fraham** [comment]
https://join.slack.com/t/papercss/shared_invite/enQtMjgwOTc1MjMyODY4LWE3NmRhZGYwZmQ0YjdlNDc3NDE3NGUyYmQ1MjMxMDkwNmMyNjMwMmNhM2FhNmVjZTg5ZWRmOTQxYmMwNTYyOWQ

**Comment by Fraham** [comment]
made a slack group, that is the invite for  people to join
