### ISSUE TITLE
Modals in CSS

### ISSUE THREAD

**Issue by afzalsayed96** [papercss/papercss#95]
Should we add a modal feature to the framework.? This can be implemented using pure CSS but with a drawback that the modal can be opened again by clicking back button or visiting the modal url.
Refer : https://www.mnishiguchi.com/2016/05/10/modal-dialog-with-pure-css/

**Comment by TotomInc** [comment]
Modals are an important point IMO in a CSS framework, even if it has some drawbacks since it's pure CSS. If you are interested in the making of this, just go and show us what it would look like for you.

**Comment by Fraham** [comment]
I think we should make a features project so we can keep track of what people are implementing

**Comment by afzalsayed96** [comment]
Assign this task to me

**Comment by afzalsayed96** [comment]
Created a PR in #102
