### ISSUE TITLE
Links on README

### ISSUE THREAD

**Issue by rhyneav** [papercss/papercss#98]
It would be beneficial to link to the other PaperCSS projects within the PaperCSS organization on the README. Maybe in a section called "Related Projects"?

Also a link to the slack channel would be great to make sure that it is used as well (#92)

**Comment by TotomInc** [comment]
I was thinking about an overhaul of the README, a more structured file and more appealing visually. Add badges, a summary, better content structure, useful links, and so on...

**Comment by TotomInc** [comment]
Done. It's actually live on the develop branch.
